// Define service categories by business type
export const serviceCategories = {
  Retail: [
    "Product Inquiry Assistance",
    "Billing & Checkout",
    "Returns & Exchanges",
    "Trial Room Access",
    "Loyalty Card Registration",
    "Store Membership Activation",
    "Gift Wrapping",
    "Online Order Pickup",
    "Damaged Product Claim",
    "Price Match Request",
    "In-Store Navigation Help",
    "Bulk Purchase Consultation",
    "Store Credit Redemption",
    "EMI/Financing Inquiry",
    "Product Demo/Live Display",
    "Warranty Information",
    "Size/Color Assistance",
    "Special Offers & Coupon Inquiry",
    "Personal Shopping Assistant",
    "Delivery Scheduling Help",
  ],
  Restaurant: [
    "Table Reservation",
    "Takeaway Pickup",
    "Menu Explanation / Food Guidance",
    "Custom Order Support",
    "Dietary Restriction Requests",
    "Special Dish Availability Check",
    "Feedback/Complaints Handling",
    "Birthday/Event Booking",
    "Advance Order Placement",
    "Digital Payment Help",
    "Buffet Queue Management",
    "Billing Correction",
    "Split Bill Assistance",
    "Waitlist Management",
    "Menu Card Request",
    "High Chair/Booster Seat Assistance",
    "Group Order Assistance",
    "Table Relocation Request",
    "Allergy Info Request",
  ],
  Salon: [
    "Haircut",
    "Hair Styling",
    "Beard Trim",
    "Hair Wash",
    "Hair Coloring",
    "Hair Straightening",
    "Head Massage",
    "Facial",
    "Cleanup",
    "Waxing (Full Body / Arms / Legs / Face)",
    "Pedicure",
    "Manicure",
    "Threading",
    "Nail Art",
    "Bridal Makeup",
    "Saree Draping",
    "Hair Spa",
    "Body Massage",
    "Skin Consultation",
    "Anti-Acne Treatment",
    "Detan Service",
    "Bleach",
    "Hair Smoothening",
    "Pre-Bridal Package Booking",
  ],
  Banking: [
    "Account Opening",
    "Loan Inquiry",
    "Cheque Book Request",
    "ATM Card Request/Block",
    "Fixed Deposit Inquiry",
    "Balance Certificate Request",
    "PAN Update Request",
    "Mobile Number Linking",
    "Statement Print",
    "Account Closure Request",
    "Demat Account Assistance",
    "Passbook Printing",
    "Credit Card Application",
    "Loan Foreclosure Process",
    "NEFT/RTGS Help",
    "Signature Update",
    "Nominee Addition",
    "Document Verification",
    "KYC Update",
    "UPI/Internet Banking Setup",
  ],
  Healthcare: [
    "Doctor Appointment Booking",
    "General Consultation",
    "Pathology Lab Test Booking",
    "Report Collection",
    "Vaccination Inquiry",
    "Health Check-Up Package Info",
    "Prescription Refill Request",
    "Insurance Claim Assistance",
    "Specialist Referral",
    "Test Result Explanation",
    "Pharmacy Queue",
    "Patient Registration",
    "Emergency Admission Request",
    "Lab Sample Collection",
    "Dental Consultation",
    "Physiotherapy Session",
    "Eye Test Booking",
    "Blood Donation Registration",
    "Hospital Bill Inquiry",
    "Second Opinion Consultation",
  ],
  Government: [
    "Aadhaar Card Update",
    "Ration Card Application",
    "Birth Certificate Application",
    "Death Certificate Request",
    "Property Tax Payment",
    "Water Bill Payment",
    "Electricity Bill Payment",
    "Voter ID Services",
    "Senior Citizen Card Request",
    "Income Certificate Issuance",
    "Domicile Certificate Application",
    "Educational Scholarship Request",
    "Disability Certificate Application",
    "Pension Application",
    "Road Tax Payment",
    "Passport Service",
    "Driving License Renewal",
    "Public Grievance Submission",
    "Document Attestation",
    "Name Correction Requests",
  ],
  Education: [
    "New Admission Inquiry",
    "Fee Payment",
    "Timetable Inquiry",
    "Certificate Request",
    "Scholarship Form Help",
    "Parent-Teacher Meeting Slot",
    "Result Collection",
    "Library Card Request",
    "Book Return",
    "Online Portal Setup",
    "Migration Certificate Request",
    "Hostel Application",
    "Bus Route Assignment",
    "Course Change Request",
    "Entrance Test Slot Booking",
    "Subject Counseling",
    "Exam Doubt Clarification",
    "Batch Transfer Request",
    "Internship Registration Help",
    "Attendance Clarification",
  ],
  Others: [
    "General Inquiry",
    "Membership Setup",
    "Complaint Registration",
    "Service Request",
    "Appointment Booking",
    "Subscription Renewal",
    "Offer Activation",
    "Ticket Booking",
    "Technical Assistance",
    "Custom Order Handling",
    "Help Desk Access",
    "Queue Bypass Request (Premium Users)",
    "Walk-in Service Help",
    "Product Demo Booking",
    "Device/Tool Setup",
    "Issue Escalation",
    "Profile Update Assistance",
    "Loyalty Reward Claim",
    "Cancellation Request",
    "Refund Status Inquiry",
  ],
  Spa: [
    "Full Body Massage",
    "Aromatherapy",
    "Steam Bath",
    "Facial",
    "Hot Stone Massage",
    "Deep Tissue Massage",
    "Swedish Massage",
    "Thai Massage",
    "Reflexology",
    "Body Scrub",
    "Body Wrap",
    "Foot Massage",
    "Head Massage",
    "Couple Massage",
    "Prenatal Massage",
    "Ayurvedic Massage",
    "Shiatsu Massage",
    "Hydrotherapy",
    "Sauna Session",
    "Detox Treatment",
  ],
}

// Get service suggestions based on business type
export const getServiceSuggestions = (businessType: string): string[] => {
  return serviceCategories[businessType as keyof typeof serviceCategories] || serviceCategories.Others
}
